/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sqlite.tutorial;

public class App {
    public static void main(String[] args) {
        System.out.println("Establishing a connection to a local DB");
        Database.run();
    }
}
